import type { AsciiOptions } from './asciiConverter';
import { DEFAULT_OPTIONS } from './asciiConverter';

export interface Preset {
  id: string;
  label: string;
  hint: string;
  apply: (base: AsciiOptions) => AsciiOptions;
}

/**
 * One-click looks. Each preset only overrides a handful of options on top of
 * whatever the user currently has so resolution / fontSize aren't blown away.
 */
export const PRESETS: Preset[] = [
  {
    id: 'photo',
    label: 'PHOTO',
    hint: 'Detailed color portrait',
    apply: (b) => ({
      ...b,
      charset: 'detailed',
      color: true,
      invert: false,
      brightness: 0,
      contrast: 10,
      saturation: 20,
      colorEnhance: 30,
      blur: 0,
      edges: false,
      dithering: false,
      density: 1,
      renderMode: 'text' as const,
      bgColor: '#05010d',
      fgColor: '#00fff5',
      charGlow: 0,
      charBrightness: 100,
      colorPalette: 'original' as const,
      gradientMap: false,
    }),
  },
  {
    id: 'sketch',
    label: 'SKETCH',
    hint: 'Edge-detected pencil',
    apply: (b) => ({
      ...b,
      charset: 'minimal',
      color: false,
      invert: true,
      brightness: 10,
      contrast: 30,
      saturation: -100,
      blur: 1,
      edges: true,
      edgeThreshold: 50,
      dithering: false,
      bgColor: '#fafafa',
      fgColor: '#0d0d0d',
    }),
  },
  {
    id: 'matrix',
    label: 'MATRIX',
    hint: 'Green code rain look',
    apply: (b) => ({
      ...b,
      charset: 'matrix',
      color: false,
      invert: false,
      brightness: 0,
      contrast: 20,
      saturation: -100,
      blur: 0,
      edges: false,
      dithering: false,
      bgColor: '#000000',
      fgColor: '#39ff14',
    }),
  },
  {
    id: 'glitch',
    label: 'GLITCH',
    hint: 'High contrast magenta',
    apply: (b) => ({
      ...b,
      charset: 'glitch',
      color: true,
      invert: false,
      brightness: -10,
      contrast: 40,
      saturation: 60,
      blur: 0,
      edges: false,
      dithering: true,
      bgColor: '#0a0014',
      fgColor: '#ff2bd6',
    }),
  },
  {
    id: 'newspaper',
    label: 'NEWSPAPER',
    hint: 'Black & white dithered',
    apply: (b) => ({
      ...b,
      charset: 'standard',
      color: false,
      invert: false,
      brightness: 0,
      contrast: 25,
      saturation: -100,
      blur: 0,
      edges: false,
      dithering: true,
      bgColor: '#f5f1e6',
      fgColor: '#0a0a0a',
    }),
  },
  {
    id: 'blocks',
    label: 'BLOCKS',
    hint: 'Pixel-art shaded blocks',
    apply: (b) => ({
      ...b,
      charset: 'blocks',
      color: true,
      invert: false,
      brightness: 0,
      contrast: 15,
      saturation: 30,
      blur: 0,
      edges: false,
      dithering: false,
      bgColor: '#000000',
      fgColor: '#ffffff',
      charGlow: 0,
      charBrightness: 100,
    }),
  },
  {
    id: 'holographic',
    label: 'HOLO',
    hint: 'Holographic glow — ASCII Magic style',
    apply: (b) => ({
      ...b,
      charset: 'ascii_magic',
      color: true,
      invert: false,
      brightness: 5,
      contrast: 25,
      saturation: 40,
      colorEnhance: 50,
      blur: 0,
      edges: false,
      dithering: false,
      density: 1,
      bgMode: 'blurred' as const,
      bgBlur: 8,
      bgOpacity: 30,
      charOpacity: 100,
      charGlow: 65,
      charBrightness: 180,
      coverage: 90,
      fx_bloom: true,
      fx_bloom_intensity: 45,
      fx_chromatic: true,
      fx_chromatic_px: 2,
      fx_vignette: true,
      fx_vignette_intensity: 35,
      fx_scanlines: false,
      fx_glitch: false,
      fx_grain: false,
    }),
  },
  {
    id: 'led_dots',
    label: 'LED',
    hint: 'Glowing dots — like LED display',
    apply: (b) => ({
      ...b,
      charset: 'dots',
      color: true,
      invert: false,
      brightness: 0,
      contrast: 20,
      saturation: 50,
      colorEnhance: 60,
      blur: 0,
      edges: false,
      dithering: false,
      density: 1.1,
      bgMode: 'solid' as const,
      bgColor: '#050510',
      charOpacity: 100,
      charGlow: 80,
      charBrightness: 200,
      coverage: 88,
      fx_bloom: true,
      fx_bloom_intensity: 55,
      fx_chromatic: false,
      fx_vignette: true,
      fx_vignette_intensity: 40,
      fx_scanlines: false,
      fx_glitch: false,
      fx_grain: false,
    }),
  },
  {
    id: 'neon_lines',
    label: 'NEON',
    hint: 'Vertical neon lines — rain look',
    apply: (b) => ({
      ...b,
      charset: 'lines',
      color: true,
      invert: false,
      brightness: -5,
      contrast: 30,
      saturation: 60,
      colorEnhance: 70,
      blur: 0,
      edges: false,
      dithering: false,
      density: 0.8,
      bgMode: 'blurred' as const,
      bgBlur: 12,
      bgOpacity: 20,
      charOpacity: 100,
      charGlow: 75,
      charBrightness: 190,
      coverage: 85,
      fx_bloom: true,
      fx_bloom_intensity: 50,
      fx_chromatic: true,
      fx_chromatic_px: 3,
      fx_vignette: true,
      fx_vignette_intensity: 45,
      fx_scanlines: true,
      fx_scanlines_intensity: 15,
      fx_glitch: false,
      fx_grain: false,
    }),
  },
  {
    id: 'pixel_hd',
    label: 'PIXEL HD',
    hint: 'Dense colored blocks — high detail',
    apply: (b) => ({
      ...b,
      charset: 'blocks',
      color: true,
      invert: false,
      brightness: 5,
      contrast: 15,
      saturation: 35,
      colorEnhance: 45,
      blur: 0,
      edges: false,
      dithering: false,
      density: 1.2,
      width: 280,
      bgMode: 'solid' as const,
      bgColor: '#000000',
      charOpacity: 100,
      charGlow: 30,
      charBrightness: 160,
      coverage: 95,
      fx_bloom: true,
      fx_bloom_intensity: 25,
      fx_chromatic: false,
      fx_vignette: false,
      fx_scanlines: false,
      fx_glitch: false,
      fx_grain: false,
    }),
  },
];

/** Returns a preset by id, or DEFAULT_OPTIONS as fallback. */
export function applyPreset(id: string, base: AsciiOptions = DEFAULT_OPTIONS): AsciiOptions {
  const p = PRESETS.find((x) => x.id === id);
  return p ? p.apply(base) : base;
}
